### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by kvannotten** [kvannotten/clipd#1]
- [x] Daemonize on startup
- [x] Make output path configurable
- [x] Make display configurable

**Comment by kvannotten** [comment]
All TODOs implemented for now.
